name: lab4
services:
  nginx:
    image: "nginx:1.25.3"
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
  flask:
    image: "scherbakovva-3/flask:1.0"
    container_name: flask
    environment:
      - FLASK_DEBUG=True
      - PYTHONUNBUFFERED=True
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    command: python app.py
  postgres:
    image: "postgres:16.1-alpine"
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: Password!
      POSTGRES_USER: flask_user
      POSTGRES_DB: flask_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

